### ISSUE TITLE
Error en el tipo de actividad

### ISSUE THREAD

**Issue by laurapaolapina** [techo/actividades#587]
**Describí el error**
Al seleccionar actividad virtual y la opción "tipo" aparece "Escuela de Voluntriado" 

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Crear actividad
2. Seleccionar tipo "virtual"
3. Seleccionar tipo "Escuela de voluntriado"
4. Ver el error

**Comportamiento esperando**
Lo esperado es que al seleccionar tipo en lugar de "voluntriado" aparezca "voluntariado"

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/64121113/84323742-5bd4fe80-ab45-11ea-9dbf-bee8f8bfbf9c.png)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador: Chrome

**Comment by agustempo** [comment]
Buenisimo Lau!
