### ISSUE TITLE
[Mejora] Boton para adjuntar capture/pdf/archivo para verificar pago

### ISSUE THREAD

**Issue by Danielfermin31** [techo/actividades#588]
**El pedido está relacionado con un problema, describí**
El problema basicamente es que hay que recurrir a otros medios (google forms) para poder verificar el pago de un inscrito/a en las actividades del sistema

**Describí la solución que te gustaría**
La solución seria que en las actividades pagas, a la hora de la pre-inscripción, haya algun boton donde poder adjuntar la prueba de pago del costo de la misma, para no tener que depender de otro sistema y/o plataforma.

**Describí alternativas que hayas considerado**
Google form y contacto directo con el inscrito (correo - número)

**Comment by agustempo** [comment]
Es muy buena la del pedido, siempre es un problema el trabajo manual para confirmar el pago.

Para darle mas vueltas a la idea, esta seria que el voluntario pueda cargar un documento que acredite el pago y que luego el usuario administrador chequee que el documento este correcto y confirme la donacion?

Saludos!

**Comment by Danielfermin31** [comment]
Hola Agus, efectivamente, seria cuention de que la persona pre-inscrita en una actividad tenga un boton para subir su comprobante de pago, a la hora de cargarlo en sistema, que el/los coordinadores puedan verificarlo, imagino seria conveniente desde la pestaña inscriptos, y asi de una vez confirmarlos, para que les llegue su respectivo correo de que fueron confirmados

**Comment by agustempo** [comment]
Se cierra este y se sigue por el siguiente [ticket](https://github.com/techo/actividades/issues/594)
