### ISSUE TITLE
Formato y campos incompletos en la descarga

### ISSUE THREAD

**Issue by h30sosa** [techo/actividades#589]
Error
En el área de personas, no están pudiendo descargar del SIV ciertos datos en el formato que ya vienen usando desde hace tiempo. Específicamente les está faltando la información de campos como: rol, fecha de la actividad y la evaluación tanto técnica como social.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a 'Admin'
2. Clickear en 'Generales/Inscriptos-evaluaciones'
3. Hacer scroll hasta '....'
4. Ver el error

**Comportamiento esperando**
En la pestaña: **Inscriptos**  La descarga de inscriptos esta incompleta, falta el campo: "evaluación"
- El campo rol está vacío

En la pestaña **Evaluaciones** falta la fecha de la actividad, y la puntación de la evaluación por actividad
- Falta el campo rol

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador chrome, chromium edge

**Contexto adicional**

**Comment by agustempo** [comment]
Herni, ahi voy por puntos

** Campo rol**
en ambas dos la columna aparece, pero en todos los casos esta en vacio porque no tienen rol asignado. 
Fijate que si probas descargando las inscripciones o evaluaciones del 2020 para la sede Tucuman veras que si muestra los roles de los voluntarixs

**Campo evaluación en inscripciones**
Al ser una descarga de inscripciones solo baja las inscripciones de todas las personas y para bajar las evaluaciones hay que combinar con el otro documento

Contame si esto te saca la duda
