### ISSUE TITLE
Error de botón de pago Construcción Posadas

### ISSUE THREAD

**Issue by h30sosa** [techo/actividades#591]
**Describí el error**
AL intentar pagar el monto de la construcción el sistema indica error

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Ir a 'https://actividades.techo.org/'
2. Clickear en 'Construcción Agosto Posadas 2020'
3. ¡Listo para pagar por la plataforma!
4. Ver el error

**Comportamiento esperando**
Integración web checkout
No se pudo crear solicitud de pago

**Capturas de pantalla**
![WhatsApp Image 2020-07-15 at 18 00 43 (1)](https://user-images.githubusercontent.com/48843144/87595955-b5d95e80-c6c5-11ea-9525-d569c71bbdee.jpeg)
![WhatsApp Image 2020-07-15 at 18 00 43](https://user-images.githubusercontent.com/48843144/87595961-b7a32200-c6c5-11ea-9df7-546242129688.jpeg)
![Error](https://user-images.githubusercontent.com/48843144/87595984-bffb5d00-c6c5-11ea-9999-b7e525deb27b.png)

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador: chrome, chromium edge, safari, firefox

**Smartphone (completá la siguiente información):**
Mismo error en todos los SO

**Contexto adicional**
Error desconocido

**Comment by agustempo** [comment]
Hernan, perdon la demora, queria contarte que estoy realizando el chequeo desde PaYU porque al parecer hubo un cambio en la configuracion de ellos, en cuanto sepa te comento mejor! Gracias

**Comment by agustempo** [comment]
Buenisimo que encontraron este error!

ya pude ver el tema y ahora se puede pagar desde PayU nuevamente.
Podes volver a probar y decirme porfa?

**Comment by agustempo** [comment]
Herni, podemos averiguar si esto esta solucionado?

**Comment by h30sosa** [comment]
Si, me respondieron que funciona, gracias crack

*Hernan Sosa | **Analista de Sistemas** | TECHO - Argentina*
Oficina: (011)
5218 0861  | Sarandí 65
<https://www.google.com/maps/place/Sarand%C3%AD+65,+C1089ACA+CABA/@-34.6101877,-58.3972789,17z/data=!3m1!4b1!4m5!3m4!1s0x95bccae8179ee433:0x8ce137d171693550!8m2!3d-34.6101877!4d-58.3950902>
,  C1089ACA, CABA, Buenos Aires, Argentina



<https://www.instagram.com/techo_argentina/>

<https://www.instagram.com/techo_argentina/>
