### ISSUE TITLE
La pestaña "Inscripciones" no funciona

### ISSUE THREAD

**Issue by Danielfermin31** [techo/actividades#593]
**Describí el error**
Al crear una actividad nueva, las personas pre-inscritas no se reflejan en la lista de la pestaña "Inscripciones". Antes (aproximadamente hace un mes) creando una actividad bajo el metodo: "**Por pago: Activo**" y "**Manual: Desactivado**" las personas que se pre-inscribian salian automaticamente en esta lista y uno solo tenia que confirmar su pago desde la opcion que da la propia lista al seleccionar uno de los inscritos, cosa que ya no pasa.

Ademas, al querer inscribir manualmente a una persona dentro de la misma pestaña de inscripciones, la opcion carga mas no avanza, se queda congelado y no inscribe a la persona.

**Para reproducirlo**
1. Pre- incribirse en una actividad.
2. Revisar la pestaña "inscripciones" de la actividad mencionada en el paso 1.
3. Verificar que la persona no sale en la lista, y a la hora de tratar de inscribirlo manualmente no se puede.

**Comportamiento esperando**
En las actividades hechas anteriormente, al usar la configurarión de pago "**Por pago: Activo**" y "**Manual: Desactivado**" las personas con solo pre-incribirse ya salian en la lista de inscripciones, cosa que ya no sucede.

**Capturas de pantalla**
Lista vacia aun habiendo 3 personas ya pre-inscritas.
![imagen](https://user-images.githubusercontent.com/66749262/87837686-5e242a00-c862-11ea-8ead-c4dab257a3ec.png)

Configuración usada de pago y verificación.
![imagen](https://user-images.githubusercontent.com/66749262/87837713-77c57180-c862-11ea-84f2-1274f1955f9f.png)

**Si estás en una computadora (por favor completá la siguiente información):**
Navegador: Firefox: Version 78.0.2 (64-bits)
S.O: Windows 10 Home

Muchas gracias.
Quedo atento.

**Comment by agustempo** [comment]
Hola Daniel, perdon la tardanza con este ticket

Ahi estuve probando y pude anotarme sin problemas, tambien vi otros inscriptos
![image](https://user-images.githubusercontent.com/11001346/88219972-c09d7180-cc38-11ea-8618-29587252293d.png)


puede ser?
Saludos

**Comment by Danielfermin31** [comment]
Hola Agus, un placer hablar de nuevo. 

Te comento, pense que era un problema del navegador ya que Firefox anda ahorita bastante agresivo con la proteccion contra rastreadores, etc y suele suceder que algunas paginas cargan mal, probe revisar desde Chrome y nada, la lista de inscritos sigue vacia, sera algun problema con mis permisos? Quizas algun ajuste nuevo está desencadenando este error? Te dejo caps de pantalla.

Lista al dia de hoy, 22/07/19 desde el navegador Firefox:
![imagen](https://user-images.githubusercontent.com/66749262/88235760-84264180-cc49-11ea-9ec4-047f9f93dd3c.png)

Lista al dia de hoy, 22/07/19 desde el navegador Chrome:
![imagen](https://user-images.githubusercontent.com/66749262/88235802-999b6b80-cc49-11ea-9742-81e48d929483.png)

**Comment by agustempo** [comment]
Dani, podes hacer CTRL+SHIFT+C desde la pagina de inscripciones?

Desde ahi fijate si te aparece un error o algo en rojo y trata de mandarme captura de ese error, te parece?


ANTES DE ESO
probar de recargar la pagina con CTRL+SHIFT+R

**Comment by Danielfermin31** [comment]
Hola Agus, disculpa mucho la demora pero estuve algo ocupado, aqui te dejo los errores que salen en la consola de Firefox:

![imagen](https://user-images.githubusercontent.com/66749262/88713075-ba037400-d0e8-11ea-80ca-7a55bd8b94ee.png)

**Comment by rubendr96** [comment]
¡Buenas! Vengo a completar la información de mi compañero Daniel, una especie de update:

**Describí el error**
El mismo de mi compañero, los usuarios pre inscritos no aparecen en la pestaña de Inscripciones. Sin embargo, y aquí la razón de esta actualización, descubrí que sí aparecen en la pestaña de Grupos.

**Capturas de pantalla**
![image](https://user-images.githubusercontent.com/55643032/90324420-abb4b500-df3c-11ea-81be-fc9627635b42.png)
Pestaña de Inscripciones. No aparece ninguno de los 19 pre inscritos.

![image](https://user-images.githubusercontent.com/55643032/90324476-5200ba80-df3d-11ea-990f-57d50b26e933.png)
Pestaña de Grupos. Si se puede visualizar todos los pre inscritos.

Si estás en una computadora (por favor completá la siguiente información):
Navegador: Chrome: Version 84.0.4147.125
S.O: Windows 10 Home (32 bits)

**Comment by agustempo** [comment]
Hola, gracias por estar aportando de esta manera a mejorar el sistema. 

Volvi a probar, y no logro tener el mismo error. Hoy en dia si ves los inscriptos?
Asi..

![image](https://user-images.githubusercontent.com/11001346/91212138-34261900-e6e6-11ea-886f-70d106e7651c.png)


y sino, queres probar de armar una prueba en el sandbox.actividades.techo.org ?
(que es el ambiente de pruebas, asi ahi podemos crear y probar tranquis,

Abrazo

**Comment by rubendr96** [comment]
¡Perfecto, Agus! Voy a crear una prueba en el Sandbox. Sin embargo, ahí no cuento con los permisos de coordinador con los que si cuento en la plataforma regular. Necesito que me asignes como coordinador o que asignes a Laura con rol de admin para que ella me asigne como coord.

**Comment by agustempo** [comment]
hola de nuevo, gracias por darle seguimiento, Celina la usuaria de Argentina encontro por que pasa esto. Al parecer el que crea la activadad con permisos admin no puede ver a los inscriptos, si los admin.

Voy a modificar esto para que si lo pueda ver y te aviso, no tenes que probar nada. Igual ya te dejo permisos de admin para la platafarma de prueba, o sandbox para los amigos... asi probas cualquier cosa que te genere dudas en la misma

**me das tu mail asi te doy permisos admin en la web de sandbox? Si no tenes tu usuario primero createlo.**

Abrazo grande y gracias por el aporte

**Comment by Danielfermin31** [comment]
Buenas tardes Agus, espero estes bien. Paso por aquí para avisar que ya, a mi, la pestaña de inscripciones me sirve, tanto en actividades creadas por mí como actividades creadas por otros y donde luego yo soy agregado como coordinador.

Espero confirmación de Rubén y ahí podriamos dar por cerrado este ticket, por fin luego de tanto buscar la raiz de este error jajajajjajajajaja.

**Comment by rubendr96** [comment]
Buenas, Agus. A mi también ya me funciona la pestaña, tanto para las actividades creadas previamente como para las nuevas. ¡Ya se puede cerrar el ticket!

**Comment by agustempo** [comment]
Que bueno que ya está funcionando ok. Gracias por los aportes y sugerencias!
