### ISSUE TITLE
[Mejora] Mejoras al correo enviado a los inscritos.

### ISSUE THREAD

**Issue by Danielfermin31** [techo/actividades#595]
**El pedido está relacionado con un problema, describí**
El correo que llega a la hora de pre-inscribirse tiene un error que puede confundir a las personas:

En cierta parte del mismo dice: **"Para confirmar tu participación, haz click en el botón Confirmar con tu donación desde Aqui"** sin embargo el link lleva a la pagina que uno pone para pagar (puede ser Google Form, Paypa, Uriji, etc) no al sistema ni a ninguna pagina con algun boton que diga "Confirmar tú donación".

**Describí la solución que te gustaría**
Que el parrafo diga: Para confirmar tu participación, haz click **AQUI** (ahi se pondria el link de pago) para realizar tú pago.

Sumado a lo anterior, crear un segundo parrafo con link, el cual, este si lleve a la pantalla dentro de la pagina donde se encuentre el botón para confirmar el pago. Por ejemplo: "Una vez hecho el pago entra **AQUI** (ahí se pondria el link del sistema para confirmar) para confirmar tú pago.

Correo actual con el error marcado.
![imagen](https://user-images.githubusercontent.com/66749262/87839672-e9ed8480-c869-11ea-8f85-5561e15714ab.png)

**Comment by agustempo** [comment]
Hola Dani, buenisimo el pedido. Como el sistema utiliza los mismos mails para todos los paises y Arg tiene configurado su metodo de pago en esos casos existe el boton "Confirmar tu donación". Para evitar complicaciones voy a cambiar el texto del mail de la siguiente manera. Asi sigue funcionando para ARG y tambien para uds.

"Para confirmar tu participación, haz click en el botón Confirmar con tu donación desde Aqui"
- por -
"Para confirmar tu participación, haz click aquí y sigue los pasos"

**Comment by Danielfermin31** [comment]
Buenisimo Agus, estoy de acuerdo, de esa forma ya se entiende el correo mas claramente y podremos evitarles confusiones a las personas que se inscriben.

Muchisimas gracias

**Comment by agustempo** [comment]
Listo Daniel, ya quedo en produccion esta nueva version!
