### ISSUE TITLE
[Mejora] ARG - Cambiar texto por motivo Colecta

### ISSUE THREAD

**Issue by h30sosa** [techo/actividades#596]
**El pedido está relacionado con un problema, describí**
Una descripción clara y concisa de cual es el problema. Por ejemplo: "Siempre me frustro cuando ..."

"Necesitamos brindar información clara en el proceso de convocatoria de voluntarios y voluntarias a la Colecta Anual de TECHO Argentina, considerando que va a ser un evento distinto al habitual y las actividades se diversificarán en presenciales o virtuales según la situación de aislamiento o distanciamiento de cada sede. Es importante realizar mejoras en la web para garantizar una convocatoria exitosa y clara".

**Describí la solución que te gustaría**Una descripción clara y concisa de que te gustaría que pase.

Una solución adecuada sería modificar el banner web contextualizando en el evento y el proceso de convocatoria y un PopUp que detalle la situación de diversificación de convocatoria que habrá según la situación de cada sede. El PopUp actual habla de suspensión de TODAS las actividades masivas presenciales y puede generar confusión en la convocatoria. 

**Describí alternativas que hayas considerado**Una descripción clara y concisa de cualquier solución alternativa que hayas considerado.

Pop Up adjunto. Texto para PopUp: COLECTA ANUAL DE TECHO ARGENTINA. " Este año la Colecta TECHO se realizará en dos modalidades: virtual o presencial, según la situación de distanciamiento o aislamiento social de cada sede. A pesar de la distancia, sigamos más juntos que nunca. ¡Conocé a qué actividad podés sumarte en tu ciudad y anotate!

**Contexto adicional** Agregá cualquier otro contexto o captura de pantalla que pueda ayudar a entender el pedido.
Adjunto header para la web y captura de pantalla del pop up actual. 

![HEADER WEB CONVOCATORIA-01](https://user-images.githubusercontent.com/48843144/88236285-023b1600-cc53-11ea-92d3-5e73a3002015.png)
![Captura_web_actividades](https://user-images.githubusercontent.com/48843144/88236289-049d7000-cc53-11ea-82ea-49879899a643.png)

**Comment by agustempo** [comment]
El pop up, para evitar los clicks demas que genera lo vamos a sacar estos dias.

Sobre el banner te parece cambiar el texto, solo en caso de Argentina, en lugar de "Si te da lo mismo... " por "COLECTA ANUAL A pesar de la distancia, sigamos más juntos que nunca."

Contame nomas!

**Comment by h30sosa** [comment]
Bro; acá las respuestas

Pop up:  si lo van a sacar entonces no vamos a poder modificarlo. Perfecto que no esté así no confunde la información.

Header: ¿No hay forma de modificarlo por el que adjunté? Ya que responde a la estética de la colecta. De ser así, esa sería la opción 1.

En caso de que no se pueda avanzar, como opción 2 propongo el cambio de texto en la web de Argentina por:

 #ColectaTECHO. A pesar de la distancia, sigamos más juntos y juntas que nunca. ¡Elegí tu ciudad y anotate!

**Comment by h30sosa** [comment]
Bro, Agus, tenemos novedad de esto?

**Comment by agustempo** [comment]
Listo Herni, ahi quedo subido para arg

![image](https://user-images.githubusercontent.com/11001346/91219552-2fb32d80-e6f1-11ea-8219-0daddaf103cc.png)
