### ISSUE TITLE
Permisos de admin

### ISSUE THREAD

**Issue by h30sosa** [techo/actividades#597]
**Describí el error**
<Reenviado>: Cambié la clave de mi usuario y al reingresar no tengo accesos de admin

Usuario:

marciaeg.meg@gmail.com

**Comment by agustempo** [comment]
hola Herni, de que ambiente hablamos? por que usuarios admin solo con mail techo.

**Comment by h30sosa** [comment]
Fe de errata:
El correo es: marcia.garcia@techo.org 

Directora de sede Tucumán

**Comment by agustempo** [comment]
Hola Herni, ahi revise y ya tiene permisos de admin
![image](https://user-images.githubusercontent.com/11001346/91484777-2906f080-e880-11ea-82c0-edff8d08ddc7.png)

Quizas esta teniendo algun problema al usar la app y piensa que son permisos.. lo ideal seria que ella misma pueda hacerse un usuario en github para levantar el problema, que te parece?
