### ISSUE TITLE
Confirmación al momento de eliminar coordinador de la actividad

### ISSUE THREAD

**Issue by rubendr96** [techo/actividades#598]
**Describí el error**
Cuando se asigna a alguien que no tiene permisos de admin o coordinador en la plataforma como coordinador de la actividad, y luego se elimina a la persona que creó la actividad como coordinador de esta, ya no le aparece la opción de poder editarla, ver los inscritos, etc.

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Crear una actividad cualquiera, abierta y pública, de prueba con usuario que tenga permisos de coordinador de la plataforma.
2. Agregar a alguien que no tenga permisos de coordinador de la plataforma como coordinador de la actividad.
3. Eliminarse o eliminar a la persona que creó la actividad como coordinador de esta.
4. Ver que la actividad aparece disponible en la plataforma; pero la persona que la creó no puede acceder a las opciones de manejo de esta.

**Comportamiento esperando**
Esperaba que apareciera una especie de pop up de alerta, solicitando una confirmación, haciendo énfasis en que una vez eliminado como coordinador de la actividad, no va a poder acceder a las opciones de manejo de esta. Como la otra persona tampoco tiene permisos de la plataforma; la actividad solo puede ser manejada por alguien con usuario que tenga permisos de admin. **Siento que el mensaje de alerta que aparece en la parte superior al campo donde se asignan nuevos coordinadores no es suficiente.**

**Capturas de pantalla**

![image](https://user-images.githubusercontent.com/55643032/90325937-f5f36180-df4f-11ea-8d4b-4b6b131af66e.png)
Actividad de prueba creada

![image](https://user-images.githubusercontent.com/55643032/90325964-2f2bd180-df50-11ea-98ca-ac84751b6686.png)
Persona sin permiso de coordinación de plataforma agregada como coordinadora de la actividad

![image](https://user-images.githubusercontent.com/55643032/90325969-4ec2fa00-df50-11ea-9f87-9264c43eaa08.png)
![image](https://user-images.githubusercontent.com/55643032/90325973-5edad980-df50-11ea-8274-72fda6e0ae53.png)
![image](https://user-images.githubusercontent.com/55643032/90325978-8336b600-df50-11ea-8441-04d59d05dc70.png)
Después de eliminarme como coordinador la actividad no me aparece para manejarla; pero sigue apareciendo disponible en la plataforma. Comparar la hora de esta captura con la anterior, no son la misma.

![image](https://user-images.githubusercontent.com/55643032/90326069-deb57380-df51-11ea-9ad4-b3cd97046ea0.png)
Después de recibir permiso de Laura, la única persona en TECHO Venezuela con permisos de admin en la plataforma, para iniciar sesión, se comprueba que la actividad sólo puede ser manejada por ella.

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador: Chrome 84.0.4147.125 (Build oficial) (32 bits)
- SO: Windows 10 Home (32 bits).

**Contexto adicional**
Realmente no sabía si añadir este requerimiento como un problema o como una solicitud de nueva funcionalidad de la plataforma. Capaz sea algo menor; pero lo considero importante y por eso el motivo de este issue.

Quedo atento ante cualquier comentario. 
Un saludo.

**Comment by agustempo** [comment]
hola Ruben, barbara la solicitud. Quizas podemos hacer que los usuarios que crean la actividad no puedan "des-Coordinarse" .. que te parece?

**Comment by rubendr96** [comment]
¡Hola Agus! Disculpa por tener esto abandonado. Si, perfecto, estoy de acuerdo con eso

**Comment by agustempo** [comment]
Listo Ruben, ya quedo modificado esto, espero lo puedas probar! Saludos

**Comment by rubendr96** [comment]
¡Perfecto! Ya revisé y está arreglado. De nuevo muchas gracias, Agus.
