### ISSUE TITLE
Error en aviso de fecha límite de pago

### ISSUE THREAD

**Issue by rubendr96** [techo/actividades#599]
**Describí el error**
Al poner una fecha límite de pago en una actividad, el mensaje de "Fecha de confirmación vencida" aparece el mismo día que se supone es la fecha límite. 

**Para reproducirlo**
Pasos para reproducir el comportamiento:
1. Crear actividad de prueba que tenga como fecha límite de pago el día actual.
2. Revisar en la lista de actividades que, efectivamente, aparece el mensaje de "Fecha de confirmación vencida automáticamente".

**Comportamiento esperando**
Si se supone que esa es la fecha límite de pago, se debería poder pagar durante ese día sin que aparezca el mensaje.
El mensaje debería aparecer justo a las 12 AM del día siguiente.

**Capturas de pantalla**

![image](https://user-images.githubusercontent.com/55643032/90326237-e5dd8100-df53-11ea-8d1a-1435118351f7.png)
![image](https://user-images.githubusercontent.com/55643032/90326245-faba1480-df53-11ea-94e3-ade7139eb0c6.png)
Se crea una actividad de prueba con fecha límite de pago del día. En este caso, 16/08/2020.

![image](https://user-images.githubusercontent.com/55643032/90326248-00aff580-df54-11ea-8d11-62ea8dc5790e.png)
Observar que aparece, por error, el mensaje el mismo día. El mensaje debería aparecer a las 12 AM del 17/08/2020.

**Si estás en una computadora (por favor completá la siguiente información):**
 - Navegador: Chrome versión 84.0.4147.125 (Build oficial) (32 bits).
- OS: Windows 10 Home (32 bits).

Quedo atento a la respuesta.
Un saludo.

**Comment by agustempo** [comment]
Buenas tardes ruben, ahi modifique para que no suceda mas este problema, gracias por  notarlo!!

Abrazo
grande
