### ISSUE TITLE
Modificaciones para solicitar la data geográfica [Mejora]

### ISSUE THREAD

**Issue by TECHOBolivia** [techo/actividades#600]
Cuando ingresas tus datos simplemente te dice: Provincia, pero no queda claro si debo llenar de dónde soy o dónde resido, imagino que lo que nos interesa es la segunda así que quizá valga la pena que diga Provincia de residencia (como es el caso de país). Esto es igual para la localidad.

**Comment by agustempo** [comment]
Hola, ahi subi esta modificacion, que te parece?

**Comment by agustempo** [comment]
![image](https://user-images.githubusercontent.com/11001346/97186536-293c4300-1780-11eb-91e3-3e4aa63af3d1.png)
