### ISSUE TITLE
División Geográfica [Mejora]

### ISSUE THREAD

**Issue by TECHOBolivia** [techo/actividades#601]
Entiendo que estandarizar a lo que le dicen en cada país para solicitar la información geográfica puede ser imposible pero a la gente le estresan estas cosas, me refiero a que me pide provincia y así no se llama en mi país o me pide localida, quizá una solución sea poner algo muy genérico como: Primera división política y Segunda división política.

**Comment by agustempo** [comment]
Mira como quedó y contame que te parece! Saludos!

![image](https://user-images.githubusercontent.com/11001346/97186482-16c20980-1780-11eb-8442-18814264bbbe.png)
