### ISSUE TITLE
[Mejora] Modificar el correo de verificación de email

### ISSUE THREAD

**Issue by TECHOBolivia** [techo/actividades#603]
El mensaje de correo automático que se recibe para la validación de la cuenta dice: Para TECHO - Argentina es importante.......

Si es posible cambiar a que simplemente diga: Para TECHO es importantes.....

![image](https://user-images.githubusercontent.com/69277586/92483531-eb2a9600-f1b6-11ea-8f10-fd744eabf0fe.png)

**Comment by agustempo** [comment]
Listo Yamil, para la proxima subida va este cambio! 

Saludos
